parameters:
    bender.03:
        - un pokemon
        - un menhir
        - des petites cacahuetes
        - de la sauce
        - une petite
        - un vieux gars
        - un geek
        - un chinois
        - un flic
        - un policier
        - un petit mexicain
        - une goudou
        - une caissiére
        - la caissiére du franprix den bas
        - un poney mort
        - un cochon d'inde
        - un jouet
        - un ours
        - un hamster
        - un cadavre
        - un nain en survetement
        - une racaille
        - un sportif
        - mon prof de sport
        - mon prof de math
