parameters:
    bender.phrase:
      - allez demain je me rase
      - dans 2 heures j'suis en week end :sunglasses:
      - darla dirla dada
      - elle était rudement bonne cette raclette
      - hier j'ai acheté 500g de viandes et j'ai tout congelé
      - j'en ai marre j'ai une reunion dans *5 minutes* :disappointed:
      - j'ai ouvert un blog !!!
      - j'ai crée un compte sur facebook
      - j'aime bien manger a la cantine
      - putain encore 2 heures de taf...
      - je viens de chier, ct terrible :toilet:
      - y a plus papier, je fais comment ? :toilet:
      - quelqu'un pour m'aider à déménager ce week end ? :truck:
