parameters:
    bender.star:
        - Aspegix
        - Grosdebilix
        - David Ghetta
        - Les Datft punk
        - Rémi gaillard
        - les Sexion d'Assaut
        - Les 1D
        - La fouine
        - Omar (de Omar et Fred)
        - Booba
        - Cyprien
        - Norman
        - Florence Foresti
        - Mimi Mathy
        - Ramzy
        - Jamel Debbouze
        - Rohff
        - M.Pokora
        - Michael Youn
        - Christophe Maé
        - Kenza Farah
        - Marion Cotillard
        - Audrey Tautou
        - Mathilde Seigner
        - Valérie Lemercier
        - Josiane Balasko
        - Jean Dujardin
        - Marina Foïs
        - Natoo
        - Kemar
        - Skeezy
